// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUzhj_MGpwfiXcWln24RtgrlyYYK7zDFg',
    appId: '1:656614580266:web:4ef60df943c2c4e0fde353',
    messagingSenderId: '656614580266',
    projectId: 'gaussapp-clientbase',
    authDomain: 'gaussapp-clientbase.firebaseapp.com',
    databaseURL: 'https://gaussapp-clientbase-default-rtdb.firebaseio.com',
    storageBucket: 'gaussapp-clientbase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_SLzPXumEFFESuzQ2rsS6kHOdT-G-9zI',
    appId: '1:656614580266:android:6c23048bc507444cfde353',
    messagingSenderId: '656614580266',
    projectId: 'gaussapp-clientbase',
    databaseURL: 'https://gaussapp-clientbase-default-rtdb.firebaseio.com',
    storageBucket: 'gaussapp-clientbase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS0k9TeBg0ldfNl57KzhBItrBceqqUi2s',
    appId: '1:656614580266:ios:68a191e3ba726711fde353',
    messagingSenderId: '656614580266',
    projectId: 'gaussapp-clientbase',
    databaseURL: 'https://gaussapp-clientbase-default-rtdb.firebaseio.com',
    storageBucket: 'gaussapp-clientbase.appspot.com',
    iosClientId: '656614580266-akp1uhful18shplkgjmq74asgp63suj8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAS0k9TeBg0ldfNl57KzhBItrBceqqUi2s',
    appId: '1:656614580266:ios:68a191e3ba726711fde353',
    messagingSenderId: '656614580266',
    projectId: 'gaussapp-clientbase',
    databaseURL: 'https://gaussapp-clientbase-default-rtdb.firebaseio.com',
    storageBucket: 'gaussapp-clientbase.appspot.com',
    iosClientId: '656614580266-akp1uhful18shplkgjmq74asgp63suj8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
